[tool.poetry]
name = "py-multithreading"
version = "0.1.0"
description = ""
authors = ["heefan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.10"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
